name: Deploy

on:
  push:
    branches: [dev, heroku-deployment]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 37adbf9e-6659-4c87-b9c4-8ee93130e9d6
          heroku_app_name: "q1-survey-service"
          heroku_email: "jophuijbers2001@gmail.com"