name: Node.js CI

on:
  push:
    branches: [ master, dev, feature/25-run-tests-on-push-or-pull-request ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: root
        ports:
          - 27017:27017
        options: >-
              --health-cmd mongo
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5

    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: ['5.0']

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Start MongoDB ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - run: npm ci
      - run: npm build --if-present
      - run: npm test