name: Node.js CI

on:
  push:
    branches: [ master, dev, feature/25-run-tests-on-push-or-pull-request ]
  pull_request:
    branches: [ master, dev ]

jobs:
  run:
    name: run

    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        options: >-
              --health-cmd mongo
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5

    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: ci and build
        run: |
          npm ci
          npm build --if-present
      
      - name: test
        run: npm test
        env:
          DATABASE_URL: mongodb://localhost:27017/JestDB
      